# The recommended basic settings for GNN
out_dir: results
accelerator: 'cuda'
devices: [0]
seed: 41
dataset:
  format: PyG
  dir: ../data
  name: Chameleon
  task: node
  task_type: classification
  transductive: true
  split: [0.6, 0.4]
  transform: none
train:
  batch_size: 128
  eval_period: 2000
  ckpt_period: 2000
  enable_ckpt: false
model:
  type: GCN
  loss_fun: cross_entropy
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 64
  layer_type: generalconv
  stage_type: stack
  batchnorm: true
  act: prelu
  dropout: 0.
  agg: add
  normalize_adj: true
optim:
  optimizer: adam
  lr_decay: 0.
  base_lr: 0.001
  max_epoch: 2000
  scheduler: none
